name: Merge main to dev

on:
  push:
    branches:
      - main

jobs:
  merge-branches:
    name: Merge main into dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test Local Action
        uses: DerTimonius/merge-branches@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branches: dev