name: Release New Version

on:
  workflow_dispatch:
    inputs:
      version_increase:
        description: "Increase Version Number By"
        required: true
        default: "prerelease"
        type: choice
        options:
        - "prerelease"
        - "patch"
        - "minor"
        - "major"


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt install -y exiftool
      - name: Checkout code
        uses: actions/checkout@v4 
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Enable Poetry
        uses: abatilo/actions-poetry@v2
      - name: Increase Version
        id: increase-version
        run: |
          poetry version ${{ inputs.version_increase }}
          echo version=$(poetry version --short) >> $GITHUB_OUTPUT
      - name: Build project
        run: poetry build
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: gh-action/bump-version
          title: Bump Version
          delete-branch: true
          commit-message: create by github action to update version number
      - name: Check Version
        id: check-version
        run: |
          [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || echo prerelease=true >> $GITHUB_OUTPUT 
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.increase-version.outputs.version }}
          draft: false
          prerelease: ${{ steps.check-version.outputs.prerelease == 'true' }}
      - name: release pypi
        if: inputs.version_increase != 'prerelease'
        run: |
          echo "RELEASING TO PyPI, tag was ${{ inputs.version_increase }}"